[2011-12-16 18:19:16] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\vendor\symfony\src\Symfony\Bundle\FrameworkBundle\EventListener\RouterListener.php line 88 [] []
[2011-12-16 18:21:20] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\vendor\symfony\src\Symfony\Bundle\FrameworkBundle\EventListener\RouterListener.php line 88 [] []
[2012-01-28 03:33:13] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-28 03:33:13] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-28 03:33:31] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-28 03:33:31] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-28 03:33:34] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-28 03:33:34] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:08:49] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:08:49] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:08:54] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:08:54] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:09:07] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:09:07] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:39] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:39] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:44] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:44] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:45] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:45] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:46] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:46] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:46] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:46] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:46] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:46] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:46] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:46] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:10:46] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:10:46] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:11:34] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:11:34] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:12:25] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:12:25] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:12:27] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:12:27] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:12:27] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:12:27] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:12:27] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:12:27] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:12:27] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:12:27] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:12:28] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:12:28] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:20:23] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:20:23] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:20:31] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:20:31] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-01-30 03:20:38] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-01-30 03:20:38] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-02-04 21:30:16] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-04 21:30:16] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-04 21:30:16] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-04 21:30:19] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-02-04 21:30:19] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\app\cache\prod\classes.php line 4533 [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-02-04 21:30:19] event.DEBUG: Notified event "kernel.controller" to listener "JMS\SecurityExtraBundle\Controller\ControllerListener::onCoreController". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:30:21] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-04 21:45:54] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-02-04 21:45:54] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /home.php" (uncaught exception) at C:\wamp\www\sky\app\cache\prod\classes.php line 4533 [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-02-04 21:45:54] event.DEBUG: Notified event "kernel.controller" to listener "JMS\SecurityExtraBundle\Controller\ControllerListener::onCoreController". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:45:55] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-04 21:46:38] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-02-04 21:46:38] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\app\cache\prod\classes.php line 4533 [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-02-04 21:46:38] event.DEBUG: Notified event "kernel.controller" to listener "JMS\SecurityExtraBundle\Controller\ControllerListener::onCoreController". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-04 21:46:39] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-09 16:38:03] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-02-09 16:38:03] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\app\cache\prod\classes.php line 4533 [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-02-09 16:38:03] event.DEBUG: Notified event "kernel.controller" to listener "JMS\SecurityExtraBundle\Controller\ControllerListener::onCoreController". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:04] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-09 16:38:12] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-02-09 16:38:12] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\app\cache\prod\classes.php line 4533 [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-02-09 16:38:12] event.DEBUG: Notified event "kernel.controller" to listener "JMS\SecurityExtraBundle\Controller\ControllerListener::onCoreController". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:13] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-09 16:38:21] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-09 16:38:21] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-09 16:38:21] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-09 16:38:22] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-02-09 16:38:22] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\wamp\www\sky\app\cache\prod\classes.php line 4533 [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onEarlyKernelRequest". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\RouterListener::onKernelRequest". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-02-09 16:38:22] event.DEBUG: Notified event "kernel.controller" to listener "JMS\SecurityExtraBundle\Controller\ControllerListener::onCoreController". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\SecurityBundle\EventListener\ResponseListener::onKernelResponse". [] []
[2012-02-09 16:38:23] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-03-17 17:32:39] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-17 17:32:40] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-03-17 17:33:12] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-17 17:33:12] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-03-17 17:33:20] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-17 17:33:20] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-03-17 17:33:30] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-17 17:33:30] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-03-24 17:37:13] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-24 17:37:13] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-03-24 17:37:21] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-24 17:37:21] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
[2012-03-24 17:37:31] request.CRITICAL: InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist. (uncaught exception) at C:\wamp\www\sky\vendor\doctrine-common\lib\Doctrine\Common\Annotations\FileCacheReader.php line 43 [] []
[2012-03-24 17:37:31] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "C:\wamp\www\sky\app/cache/prod_new/annotations" does not exist.) [] []
